import type {
  AdminDashboardSnapshot,
  AiReviewQuestion,
  ModuleAsset,
  ModuleSection,
  StaffDashboardSnapshot,
  TrainingModule,
} from "@/domain/academy/entities";
import type { AcademyRepository } from "@/domain/academy/repositories";

function createStandardResources(slug: string, title: string): ModuleAsset[] {
  return [
    {
      id: `${slug}-video`,
      title: `${title} walkthrough`,
      kind: "video",
      meta: "MP4 placeholder · 1080p",
      description: `Primary lesson video placeholder for ${title}.`,
      status: "published",
    },
    {
      id: `${slug}-audio`,
      title: `${title} narrated summary`,
      kind: "audio",
      meta: "Audio placeholder · 5 min",
      description: `Narration or recap audio for ${title}.`,
      status: "published",
    },
    {
      id: `${slug}-policy-pack`,
      title: `${title} policy pack`,
      kind: "document",
      meta: "PDF · 12 pages",
      description: `Reference document bundle attached to ${title}.`,
      status: "published",
    },
    {
      id: `${slug}-worksheet`,
      title: `${title} facilitator worksheet`,
      kind: "worksheet",
      meta: "DOCX placeholder · editable",
      description: `Editable staff worksheet for follow-up discussions on ${title}.`,
      status: "draft",
    },
  ];
}

function createStandardSections(slug: string, title: string): ModuleSection[] {
  return [
    {
      id: "why-this-matters",
      order: 1,
      title: "Why this matters",
      summary: "Context and policy framing",
      durationLabel: "5 min",
      kind: "video",
      isComplete: slug === "school-code-of-conduct",
      mediaTitle: `${title}: orientation`,
      mediaDescription: `Opening lesson placeholder introducing ${title}.`,
      documentIds: [`${slug}-policy-pack`],
    },
    {
      id: "key-guidelines",
      order: 2,
      title: "Key guidelines",
      summary: "Practical staff guidance",
      durationLabel: "7 min",
      kind: "reading",
      isComplete: slug === "school-code-of-conduct",
      mediaTitle: `${title}: guidance review`,
      mediaDescription: `A guided content placeholder covering the key guidelines in ${title}.`,
      documentIds: [`${slug}-policy-pack`, `${slug}-worksheet`],
    },
    {
      id: "real-world-scenarios",
      order: 3,
      title: "Real-world scenarios",
      summary: "Case studies and examples",
      durationLabel: "6 min",
      kind: "case-study",
      isCurrent: slug === "learner-discipline",
      mediaTitle: `${title}: scenario walkthrough`,
      mediaDescription: `Scenario-based content placeholder for ${title}.`,
      scenarioTitle: `${title}: scenario walkthrough`,
      scenarioBody: `This lesson is where staff work through realistic ${title.toLowerCase()} scenarios and apply the school policy consistently.`,
      reflectionPrompt:
        "Pause here and identify the safest, most policy-aligned next step before moving on.",
      documentIds: [`${slug}-policy-pack`],
    },
    {
      id: "your-responsibilities",
      order: 4,
      title: "Your responsibilities",
      summary: "What staff are expected to do",
      durationLabel: "5 min",
      kind: "audio",
      mediaTitle: `${title}: role expectations`,
      mediaDescription: `Audio placeholder summarising staff responsibilities in ${title}.`,
      documentIds: [`${slug}-worksheet`],
    },
    {
      id: "module-assessment",
      order: 5,
      title: "Module assessment",
      summary: "Knowledge check and sign-off",
      durationLabel: "Quiz",
      kind: "assessment",
      mediaTitle: `${title}: assessment`,
      mediaDescription: `Assessment placeholder for ${title}.`,
      documentIds: [`${slug}-policy-pack`],
    },
  ];
}

const socialMediaResources: ModuleAsset[] = [
  {
    id: "social-media-awareness-video",
    title: "Social Media Awareness lesson reel",
    kind: "video",
    meta: "MP4 placeholder · 6 min",
    description: "Main video placeholder used in the academy lesson player.",
    status: "published",
  },
  {
    id: "social-media-awareness-audio",
    title: "Narrated acceptable use summary",
    kind: "audio",
    meta: "Audio placeholder · 4 min",
    description: "Narrated recap for busy staff who want the policy summary in audio form.",
    status: "published",
  },
  {
    id: "social-media-awareness-policy",
    title: "Social media policy handbook",
    kind: "document",
    meta: "PDF · 14 pages",
    description: "Primary policy document shown alongside the learner-side module.",
    status: "published",
  },
  {
    id: "social-media-awareness-checklist",
    title: "Incident response checklist",
    kind: "worksheet",
    meta: "DOCX placeholder · editable",
    description: "Downloadable checklist for staff handling social-media incidents.",
    status: "draft",
  },
];

const socialMediaSections: ModuleSection[] = [
  {
    id: "why-this-matters",
    order: 1,
    title: "Why this matters",
    summary: "Narrated intro",
    durationLabel: "4 min",
    kind: "audio",
    isComplete: true,
    mediaTitle: "Opening briefing",
    mediaDescription:
      "Audio placeholder introducing why personal social-media conduct affects the school.",
    documentIds: ["social-media-awareness-policy"],
  },
  {
    id: "acceptable-use",
    order: 2,
    title: "What is acceptable use?",
    summary: "Narrated + visuals",
    durationLabel: "8 min",
    kind: "reading",
    isComplete: true,
    mediaTitle: "Acceptable use breakdown",
    mediaDescription: "Video placeholder showing acceptable use examples and policy highlights.",
    documentIds: ["social-media-awareness-policy", "social-media-awareness-checklist"],
  },
  {
    id: "real-world-scenarios",
    order: 3,
    title: "Real-world scenarios",
    summary: "Case studies",
    durationLabel: "6 min",
    kind: "case-study",
    isCurrent: true,
    mediaTitle: "Scenario review",
    mediaDescription: "Video placeholder for guided case-study analysis.",
    scenarioTitle: "Scenario: The viral parent post",
    scenarioBody:
      "A parent posts a complaint about Cliffview on a community Facebook group. Within an hour it has 200 shares. Three staff members have already been tagged in the comments.",
    reflectionPrompt: "Take a moment before the next slide. The right move is not the loudest one.",
    documentIds: ["social-media-awareness-policy", "social-media-awareness-checklist"],
  },
  {
    id: "your-responsibilities",
    order: 4,
    title: "Your responsibilities",
    summary: "Narrated summary",
    durationLabel: "5 min",
    kind: "audio",
    mediaTitle: "Responsibilities recap",
    mediaDescription:
      "Audio placeholder that closes the module with staff obligations and escalation reminders.",
    documentIds: ["social-media-awareness-checklist"],
  },
  {
    id: "module-assessment",
    order: 5,
    title: "Module Assessment",
    summary: "AI-generated questions",
    durationLabel: "Quiz",
    kind: "assessment",
    mediaTitle: "Assessment view",
    mediaDescription: "Assessment placeholder before backend question delivery is added.",
    documentIds: ["social-media-awareness-policy"],
  },
];

const modules: TrainingModule[] = [
  {
    id: "module-01",
    number: "01",
    slug: "school-code-of-conduct",
    title: "School Code of Conduct",
    category: "Core Policies",
    description: "Core behaviour standards, staff expectations, and escalation boundaries.",
    audience: "All staff",
    outcome: "Build confidence applying the school code consistently across everyday decisions.",
    durationMinutes: 30,
    sectionCount: 4,
    cptdPoints: 2,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 100,
    status: "complete",
    learningObjectives: [
      "Recognise the core behavioural standards expected of staff.",
      "Apply the code consistently when dealing with learners and families.",
      "Use the right escalation path when boundaries are crossed.",
    ],
    featuredAssetId: "school-code-of-conduct-video",
    resources: createStandardResources("school-code-of-conduct", "School Code of Conduct"),
    sections: createStandardSections("school-code-of-conduct", "School Code of Conduct"),
    lastUpdatedLabel: "Updated 2 days ago",
  },
  {
    id: "module-02",
    number: "02",
    slug: "social-media-awareness",
    title: "Social Media Awareness",
    category: "Core Policies",
    description:
      "How Cliffview staff represent the school online: what is expected, what is not, and how to respond when things go sideways.",
    audience: "Teaching staff and school-facing support teams",
    outcome:
      "Help staff respond to online incidents without escalating legal, reputational, or safeguarding risk.",
    durationMinutes: 23,
    sectionCount: 4,
    cptdPoints: 3,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 65,
    status: "in-progress",
    learningObjectives: [
      "Identify the difference between personal posting and school representation.",
      "Recognise risky public responses and choose policy-safe alternatives.",
      "Use the right documents and escalation paths during social-media incidents.",
    ],
    featuredAssetId: "social-media-awareness-video",
    resources: socialMediaResources,
    sections: socialMediaSections,
    lastUpdatedLabel: "Updated today",
  },
  {
    id: "module-03",
    number: "03",
    slug: "learner-discipline",
    title: "Learner Discipline",
    category: "Core Policies",
    description: "Discipline workflows, due process, and practical classroom interventions.",
    audience: "Teachers, heads of department, and pastoral staff",
    outcome:
      "Give staff a repeatable discipline response that is fair, documentable, and aligned to policy.",
    durationMinutes: 25,
    sectionCount: 4,
    cptdPoints: 2,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 0,
    status: "available",
    learningObjectives: [
      "Choose the right intervention for low, medium, and high-severity behaviour issues.",
      "Document incidents in a way SMT can act on.",
      "Maintain due process while protecting the classroom environment.",
    ],
    featuredAssetId: "learner-discipline-video",
    resources: createStandardResources("learner-discipline", "Learner Discipline"),
    sections: createStandardSections("learner-discipline", "Learner Discipline"),
    lastUpdatedLabel: "Updated yesterday",
  },
  {
    id: "module-04",
    number: "04",
    slug: "health-and-safety",
    title: "Health & Safety",
    category: "Core Policies",
    description: "Operational readiness, incident response, and reporting requirements.",
    audience: "All operational and teaching staff",
    outcome:
      "Ensure staff can respond quickly, log incidents properly, and protect learners during disruptions.",
    durationMinutes: 20,
    sectionCount: 3,
    cptdPoints: 2,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 0,
    status: "locked",
    learningObjectives: [
      "Recognise the immediate steps required during school safety incidents.",
      "Use reporting templates consistently.",
      "Know which documents and contacts are required during escalation.",
    ],
    featuredAssetId: "health-and-safety-video",
    resources: createStandardResources("health-and-safety", "Health & Safety"),
    sections: createStandardSections("health-and-safety", "Health & Safety"),
    lastUpdatedLabel: "Updated 4 days ago",
  },
  {
    id: "module-05",
    number: "05",
    slug: "safeguarding-and-reporting",
    title: "Safeguarding & Reporting",
    category: "Core Policies",
    description: "Escalation duties, safeguarding signals, and statutory reporting expectations.",
    audience: "Teachers, student-facing support staff, and SMT",
    outcome: "Strengthen response quality when a learner disclosure or welfare concern is raised.",
    durationMinutes: 35,
    sectionCount: 5,
    cptdPoints: 3,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 0,
    status: "locked",
    learningObjectives: [
      "Identify reportable safeguarding concerns faster.",
      "Use immediate response language that protects learners.",
      "Complete the right reporting steps without delay.",
    ],
    featuredAssetId: "safeguarding-and-reporting-video",
    resources: createStandardResources("safeguarding-and-reporting", "Safeguarding & Reporting"),
    sections: createStandardSections("safeguarding-and-reporting", "Safeguarding & Reporting"),
    lastUpdatedLabel: "Updated 1 week ago",
  },
  {
    id: "module-06",
    number: "06",
    slug: "disciplinary-hearings",
    title: "Disciplinary Hearings",
    category: "SMT Pathway",
    description: "Preparation, notices, hearing conduct, and defensible documentation.",
    audience: "Senior management and disciplinary panel leads",
    outcome: "Help SMT run hearings that are procedurally sound and clearly documented.",
    durationMinutes: 45,
    sectionCount: 6,
    cptdPoints: 4,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 0,
    status: "locked",
    learningObjectives: [
      "Prepare hearing packs correctly.",
      "Run hearings with defensible documentation.",
      "Separate process from emotion during complex cases.",
    ],
    featuredAssetId: "disciplinary-hearings-video",
    resources: createStandardResources("disciplinary-hearings", "Disciplinary Hearings"),
    sections: createStandardSections("disciplinary-hearings", "Disciplinary Hearings"),
    lastUpdatedLabel: "Updated 3 days ago",
  },
  {
    id: "module-07",
    number: "07",
    slug: "sasa-and-bela-compliance",
    title: "SASA & BELA Compliance",
    category: "SMT Pathway",
    description: "Policy obligations and operational changes arising from current school law.",
    audience: "Senior management and policy owners",
    outcome:
      "Translate regulation changes into practical school procedures and documented controls.",
    durationMinutes: 40,
    sectionCount: 5,
    cptdPoints: 4,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 0,
    status: "locked",
    learningObjectives: [
      "Identify the school procedures affected by new legal requirements.",
      "Spot compliance gaps before audit or incident review.",
      "Prepare policy updates and communications for staff rollout.",
    ],
    featuredAssetId: "sasa-and-bela-compliance-video",
    resources: createStandardResources("sasa-and-bela-compliance", "SASA & BELA Compliance"),
    sections: createStandardSections("sasa-and-bela-compliance", "SASA & BELA Compliance"),
    lastUpdatedLabel: "Updated today",
  },
  {
    id: "module-08",
    number: "08",
    slug: "responsible-ai-usage",
    title: "Responsible AI Usage",
    category: "Staff Development",
    description: "School-safe AI usage, review requirements, and data handling boundaries.",
    audience: "All staff using generative tools for planning or communication",
    outcome: "Help staff use AI productively without creating privacy, safety, or accuracy risks.",
    durationMinutes: 30,
    sectionCount: 4,
    cptdPoints: 2,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 0,
    status: "locked",
    learningObjectives: [
      "Use AI within approved data and privacy boundaries.",
      "Recognise when AI output still needs human review.",
      "Document responsible usage in school workflows.",
    ],
    featuredAssetId: "responsible-ai-usage-video",
    resources: createStandardResources("responsible-ai-usage", "Responsible AI Usage"),
    sections: createStandardSections("responsible-ai-usage", "Responsible AI Usage"),
    lastUpdatedLabel: "Updated 5 days ago",
  },
  {
    id: "module-09",
    number: "09",
    slug: "parent-communication-protocol",
    title: "Parent Communication Protocol",
    category: "Staff Development",
    description:
      "A practical communication module for handling sensitive parent messages, escalations, and follow-up documentation across email, WhatsApp, and meetings.",
    audience: "Teachers, grade leads, front office staff, and pastoral teams",
    outcome:
      "Give staff a clear communication structure so parent interactions stay calm, documented, and aligned with school expectations.",
    durationMinutes: 28,
    sectionCount: 4,
    cptdPoints: 3,
    passMark: 80,
    format: "Self-paced",
    progressPercent: 0,
    status: "available",
    learningObjectives: [
      "Identify when to acknowledge, escalate, or move a parent conversation offline.",
      "Use school-approved language when responding to emotional or high-risk messages.",
      "Attach the right supporting documents and meeting notes after each interaction.",
    ],
    featuredAssetId: "parent-communication-protocol-video",
    resources: [
      {
        id: "parent-communication-protocol-video",
        title: "Parent communication overview reel",
        kind: "video",
        meta: "MP4 placeholder · 7 min",
        description: "Hero lesson video placeholder introducing the communication framework.",
        status: "published",
      },
      {
        id: "parent-communication-protocol-audio",
        title: "Escalation script audio",
        kind: "audio",
        meta: "Audio placeholder · 3 min",
        description: "Audio recap of the escalation script staff can listen to on the go.",
        status: "published",
      },
      {
        id: "parent-communication-protocol-templates",
        title: "Email and meeting note templates",
        kind: "document",
        meta: "PDF placeholder · 9 pages",
        description:
          "Downloadable message templates, acknowledgement language, and meeting note layouts.",
        status: "published",
      },
      {
        id: "parent-communication-protocol-checklist",
        title: "Escalation checklist",
        kind: "worksheet",
        meta: "DOCX placeholder · editable",
        description: "Editable escalation checklist attached to the learner-facing module.",
        status: "draft",
      },
    ],
    sections: [
      {
        id: "message-triage",
        order: 1,
        title: "Message triage",
        summary: "Classify the message and choose the right lane",
        durationLabel: "6 min",
        kind: "video",
        mediaTitle: "Triage framework",
        mediaDescription:
          "Video placeholder explaining how staff sort parent messages by urgency and channel.",
        scenarioTitle: "Scenario: The Friday-night complaint",
        scenarioBody:
          "A parent sends a frustrated WhatsApp message at 20:45 on Friday night and copies two other parents into the thread. The issue is emotional but not yet a safeguarding concern.",
        reflectionPrompt:
          "Before replying, decide whether the issue needs acknowledgement, escalation, or a scheduled conversation.",
        documentIds: ["parent-communication-protocol-templates"],
      },
      {
        id: "response-language",
        order: 2,
        title: "Response language",
        summary: "Tone, boundaries, and approved wording",
        durationLabel: "8 min",
        kind: "reading",
        mediaTitle: "Response language walkthrough",
        mediaDescription:
          "Lesson placeholder with approved wording patterns for difficult conversations.",
        documentIds: [
          "parent-communication-protocol-templates",
          "parent-communication-protocol-checklist",
        ],
      },
      {
        id: "meeting-preparation",
        order: 3,
        title: "Meeting preparation",
        summary: "Prepare notes, facts, and participants",
        durationLabel: "7 min",
        kind: "case-study",
        isCurrent: true,
        mediaTitle: "Meeting prep scenario",
        mediaDescription:
          "Case-study placeholder showing how to prepare for an escalated parent meeting.",
        scenarioTitle: "Scenario: Escalating to a grade-level meeting",
        scenarioBody:
          "A recurring classroom concern has now become a meeting request involving the grade head. Staff need a consistent packet of facts, previous communication, and next-step options.",
        reflectionPrompt:
          "What should be documented before the meeting begins, and what should never be improvised live?",
        documentIds: [
          "parent-communication-protocol-templates",
          "parent-communication-protocol-checklist",
        ],
      },
      {
        id: "module-assessment",
        order: 4,
        title: "Module assessment",
        summary: "Knowledge check and sign-off",
        durationLabel: "Quiz",
        kind: "assessment",
        mediaTitle: "Assessment placeholder",
        mediaDescription: "Assessment placeholder before backend question delivery is connected.",
        documentIds: ["parent-communication-protocol-templates"],
      },
    ],
    lastUpdatedLabel: "Draft synced 10 minutes ago",
  },
];

const staffDashboardSnapshot: StaffDashboardSnapshot = {
  staffMember: {
    id: "staff-01",
    firstName: "Priya",
    lastName: "Ms. Naidoo",
    role: "Teacher",
    phase: "Foundation Phase",
  },
  dateLabel: "Wednesday, 19 May 2026",
  completedModuleCount: 3,
  totalModuleCount: 12,
  xpEarnedThisMonth: 1240,
  cptdPointsYearToDate: 12,
  streakDays: 7,
  activeModuleSlug: "social-media-awareness",
  activeModuleSectionLabel: "Section 3 of 4: Real-world scenarios",
  activeModuleProgressPercent: 65,
  remainingMinutes: 12,
  upcomingModuleSlugs: ["learner-discipline", "health-and-safety"],
  leaderboard: [
    { rank: 1, participantName: "Ms. Naidoo (you)", xp: 1240, isCurrentUser: true },
    { rank: 2, participantName: "Mr. van Wyk", xp: 1180 },
    { rank: 3, participantName: "Mrs. Dlamini", xp: 1095 },
    { rank: 4, participantName: "Mr. Pillay", xp: 970 },
  ],
  recentAchievements: ["First Module", "3-Day Streak", "Top 5"],
};

const adminDashboardSnapshot: AdminDashboardSnapshot = {
  dateLabel: "Wednesday, 19 May 2026",
  totalStaff: 42,
  activeAccountsDelta: 2,
  completedModules: 127,
  completedModulesDelta: 18,
  averageCompliancePercent: 73,
  averageComplianceDeltaPercent: 5,
  pendingAiReviewCount: 8,
  editedAiReviewCount: 12,
  phases: [
    { name: "Foundation Phase", completionPercent: 82 },
    { name: "Intersen Phase", completionPercent: 68 },
    { name: "Senior Management", completionPercent: 91 },
    { name: "Support Staff", completionPercent: 55 },
  ],
  completionTrend: [
    { month: "Dec", completedModules: 12 },
    { month: "Jan", completedModules: 28 },
    { month: "Feb", completedModules: 45 },
    { month: "Mar", completedModules: 67 },
    { month: "Apr", completedModules: 109 },
    { month: "May", completedModules: 127 },
  ],
};

const aiReviewQuestions: AiReviewQuestion[] = [
  {
    id: 1,
    moduleTitle: "Disciplinary Hearings",
    difficulty: "Medium",
    confidencePercent: 94,
    prompt: "Which document must be served before a disciplinary hearing under SASA?",
    options: [
      { key: "A", text: "Notice of Hearing", isCorrect: true },
      { key: "B", text: "Verbal warning letter" },
      { key: "C", text: "School circular" },
      { key: "D", text: "Email summary" },
    ],
  },
  {
    id: 2,
    moduleTitle: "Safeguarding & Reporting",
    difficulty: "Hard",
    confidencePercent: 89,
    prompt:
      "A learner discloses abuse outside school hours. Within what timeframe must you report?",
    options: [
      { key: "A", text: "24 hours" },
      { key: "B", text: "Immediately", isCorrect: true },
      { key: "C", text: "End of next school day" },
      { key: "D", text: "After confirming with parents" },
    ],
  },
];

export class InMemoryAcademyRepository implements AcademyRepository {
  getStaffDashboardSnapshot() {
    return staffDashboardSnapshot;
  }

  listTrainingModules() {
    return modules;
  }

  getTrainingModuleBySlug(slug: string) {
    return modules.find((module) => module.slug === slug);
  }

  getAdminDashboardSnapshot() {
    return adminDashboardSnapshot;
  }

  listAiReviewQuestions() {
    return aiReviewQuestions;
  }
}
