/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademySignInRouteImport } from './routes/academy.sign-in'
import { Route as AcademyProfileRouteImport } from './routes/academy.profile'
import { Route as AcademyModulesRouteImport } from './routes/academy.modules'
import { Route as AcademyLeaderboardRouteImport } from './routes/academy.leaderboard'
import { Route as AcademyInviteRouteImport } from './routes/academy.invite'
import { Route as AcademyDashboardRouteImport } from './routes/academy.dashboard'
import { Route as AcademyAdminRouteImport } from './routes/academy.admin'
import { Route as AcademyModulesIndexRouteImport } from './routes/academy.modules.index'
import { Route as AcademyAdminIndexRouteImport } from './routes/academy.admin.index'
import { Route as AcademyModulesModuleSlugRouteImport } from './routes/academy.modules.$moduleSlug'
import { Route as AcademyAdminSignInRouteImport } from './routes/academy.admin_.sign-in'
import { Route as AcademyAdminStaffRouteImport } from './routes/academy.admin.staff'
import { Route as AcademyAdminModulesRouteImport } from './routes/academy.admin.modules'
import { Route as AcademyAdminAiReviewRouteImport } from './routes/academy.admin.ai-review'
import { Route as AcademyModulesModuleSlugIndexRouteImport } from './routes/academy.modules.$moduleSlug.index'
import { Route as AcademyAdminStaffIndexRouteImport } from './routes/academy.admin.staff.index'
import { Route as AcademyAdminModulesIndexRouteImport } from './routes/academy.admin.modules.index'
import { Route as AcademyAdminStaffStaffIdRouteImport } from './routes/academy.admin.staff.$staffId'
import { Route as AcademyAdminModulesCreateRouteImport } from './routes/academy.admin.modules.create'
import { Route as AcademyAdminModulesModuleSlugRouteImport } from './routes/academy.admin.modules.$moduleSlug'
import { Route as AcademyAdminModulesModuleSlugIndexRouteImport } from './routes/academy.admin.modules.$moduleSlug.index'
import { Route as AcademyModulesModuleSlugLessonLessonIdRouteImport } from './routes/academy.modules.$moduleSlug.lesson.$lessonId'
import { Route as AcademyAdminModulesModuleSlugLessonsLessonIdRouteImport } from './routes/academy.admin.modules.$moduleSlug.lessons.$lessonId'
import { Route as AcademyAdminModulesModuleSlugAssetsAssetIdRouteImport } from './routes/academy.admin.modules.$moduleSlug.assets.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySignInRoute = AcademySignInRouteImport.update({
  id: '/academy/sign-in',
  path: '/academy/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyProfileRoute = AcademyProfileRouteImport.update({
  id: '/academy/profile',
  path: '/academy/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyModulesRoute = AcademyModulesRouteImport.update({
  id: '/academy/modules',
  path: '/academy/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyLeaderboardRoute = AcademyLeaderboardRouteImport.update({
  id: '/academy/leaderboard',
  path: '/academy/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyInviteRoute = AcademyInviteRouteImport.update({
  id: '/academy/invite',
  path: '/academy/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyDashboardRoute = AcademyDashboardRouteImport.update({
  id: '/academy/dashboard',
  path: '/academy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAdminRoute = AcademyAdminRouteImport.update({
  id: '/academy/admin',
  path: '/academy/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyModulesIndexRoute = AcademyModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyModulesRoute,
} as any)
const AcademyAdminIndexRoute = AcademyAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyAdminRoute,
} as any)
const AcademyModulesModuleSlugRoute =
  AcademyModulesModuleSlugRouteImport.update({
    id: '/$moduleSlug',
    path: '/$moduleSlug',
    getParentRoute: () => AcademyModulesRoute,
  } as any)
const AcademyAdminSignInRoute = AcademyAdminSignInRouteImport.update({
  id: '/academy/admin_/sign-in',
  path: '/academy/admin/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAdminStaffRoute = AcademyAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AcademyAdminRoute,
} as any)
const AcademyAdminModulesRoute = AcademyAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AcademyAdminRoute,
} as any)
const AcademyAdminAiReviewRoute = AcademyAdminAiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => AcademyAdminRoute,
} as any)
const AcademyModulesModuleSlugIndexRoute =
  AcademyModulesModuleSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AcademyModulesModuleSlugRoute,
  } as any)
const AcademyAdminStaffIndexRoute = AcademyAdminStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyAdminStaffRoute,
} as any)
const AcademyAdminModulesIndexRoute =
  AcademyAdminModulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AcademyAdminModulesRoute,
  } as any)
const AcademyAdminStaffStaffIdRoute =
  AcademyAdminStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AcademyAdminStaffRoute,
  } as any)
const AcademyAdminModulesCreateRoute =
  AcademyAdminModulesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AcademyAdminModulesRoute,
  } as any)
const AcademyAdminModulesModuleSlugRoute =
  AcademyAdminModulesModuleSlugRouteImport.update({
    id: '/$moduleSlug',
    path: '/$moduleSlug',
    getParentRoute: () => AcademyAdminModulesRoute,
  } as any)
const AcademyAdminModulesModuleSlugIndexRoute =
  AcademyAdminModulesModuleSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AcademyAdminModulesModuleSlugRoute,
  } as any)
const AcademyModulesModuleSlugLessonLessonIdRoute =
  AcademyModulesModuleSlugLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AcademyModulesModuleSlugRoute,
  } as any)
const AcademyAdminModulesModuleSlugLessonsLessonIdRoute =
  AcademyAdminModulesModuleSlugLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AcademyAdminModulesModuleSlugRoute,
  } as any)
const AcademyAdminModulesModuleSlugAssetsAssetIdRoute =
  AcademyAdminModulesModuleSlugAssetsAssetIdRouteImport.update({
    id: '/assets/$assetId',
    path: '/assets/$assetId',
    getParentRoute: () => AcademyAdminModulesModuleSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/invite': typeof AcademyInviteRoute
  '/academy/leaderboard': typeof AcademyLeaderboardRoute
  '/academy/modules': typeof AcademyModulesRouteWithChildren
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/sign-in': typeof AcademySignInRoute
  '/academy/admin/ai-review': typeof AcademyAdminAiReviewRoute
  '/academy/admin/modules': typeof AcademyAdminModulesRouteWithChildren
  '/academy/admin/staff': typeof AcademyAdminStaffRouteWithChildren
  '/academy/admin/sign-in': typeof AcademyAdminSignInRoute
  '/academy/modules/$moduleSlug': typeof AcademyModulesModuleSlugRouteWithChildren
  '/academy/admin/': typeof AcademyAdminIndexRoute
  '/academy/modules/': typeof AcademyModulesIndexRoute
  '/academy/admin/modules/$moduleSlug': typeof AcademyAdminModulesModuleSlugRouteWithChildren
  '/academy/admin/modules/create': typeof AcademyAdminModulesCreateRoute
  '/academy/admin/staff/$staffId': typeof AcademyAdminStaffStaffIdRoute
  '/academy/admin/modules/': typeof AcademyAdminModulesIndexRoute
  '/academy/admin/staff/': typeof AcademyAdminStaffIndexRoute
  '/academy/modules/$moduleSlug/': typeof AcademyModulesModuleSlugIndexRoute
  '/academy/modules/$moduleSlug/lesson/$lessonId': typeof AcademyModulesModuleSlugLessonLessonIdRoute
  '/academy/admin/modules/$moduleSlug/': typeof AcademyAdminModulesModuleSlugIndexRoute
  '/academy/admin/modules/$moduleSlug/assets/$assetId': typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  '/academy/admin/modules/$moduleSlug/lessons/$lessonId': typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/invite': typeof AcademyInviteRoute
  '/academy/leaderboard': typeof AcademyLeaderboardRoute
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/sign-in': typeof AcademySignInRoute
  '/academy/admin/ai-review': typeof AcademyAdminAiReviewRoute
  '/academy/admin/sign-in': typeof AcademyAdminSignInRoute
  '/academy/admin': typeof AcademyAdminIndexRoute
  '/academy/modules': typeof AcademyModulesIndexRoute
  '/academy/admin/modules/create': typeof AcademyAdminModulesCreateRoute
  '/academy/admin/staff/$staffId': typeof AcademyAdminStaffStaffIdRoute
  '/academy/admin/modules': typeof AcademyAdminModulesIndexRoute
  '/academy/admin/staff': typeof AcademyAdminStaffIndexRoute
  '/academy/modules/$moduleSlug': typeof AcademyModulesModuleSlugIndexRoute
  '/academy/modules/$moduleSlug/lesson/$lessonId': typeof AcademyModulesModuleSlugLessonLessonIdRoute
  '/academy/admin/modules/$moduleSlug': typeof AcademyAdminModulesModuleSlugIndexRoute
  '/academy/admin/modules/$moduleSlug/assets/$assetId': typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  '/academy/admin/modules/$moduleSlug/lessons/$lessonId': typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/invite': typeof AcademyInviteRoute
  '/academy/leaderboard': typeof AcademyLeaderboardRoute
  '/academy/modules': typeof AcademyModulesRouteWithChildren
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/sign-in': typeof AcademySignInRoute
  '/academy/admin/ai-review': typeof AcademyAdminAiReviewRoute
  '/academy/admin/modules': typeof AcademyAdminModulesRouteWithChildren
  '/academy/admin/staff': typeof AcademyAdminStaffRouteWithChildren
  '/academy/admin_/sign-in': typeof AcademyAdminSignInRoute
  '/academy/modules/$moduleSlug': typeof AcademyModulesModuleSlugRouteWithChildren
  '/academy/admin/': typeof AcademyAdminIndexRoute
  '/academy/modules/': typeof AcademyModulesIndexRoute
  '/academy/admin/modules/$moduleSlug': typeof AcademyAdminModulesModuleSlugRouteWithChildren
  '/academy/admin/modules/create': typeof AcademyAdminModulesCreateRoute
  '/academy/admin/staff/$staffId': typeof AcademyAdminStaffStaffIdRoute
  '/academy/admin/modules/': typeof AcademyAdminModulesIndexRoute
  '/academy/admin/staff/': typeof AcademyAdminStaffIndexRoute
  '/academy/modules/$moduleSlug/': typeof AcademyModulesModuleSlugIndexRoute
  '/academy/modules/$moduleSlug/lesson/$lessonId': typeof AcademyModulesModuleSlugLessonLessonIdRoute
  '/academy/admin/modules/$moduleSlug/': typeof AcademyAdminModulesModuleSlugIndexRoute
  '/academy/admin/modules/$moduleSlug/assets/$assetId': typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  '/academy/admin/modules/$moduleSlug/lessons/$lessonId': typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy/admin'
    | '/academy/dashboard'
    | '/academy/invite'
    | '/academy/leaderboard'
    | '/academy/modules'
    | '/academy/profile'
    | '/academy/sign-in'
    | '/academy/admin/ai-review'
    | '/academy/admin/modules'
    | '/academy/admin/staff'
    | '/academy/admin/sign-in'
    | '/academy/modules/$moduleSlug'
    | '/academy/admin/'
    | '/academy/modules/'
    | '/academy/admin/modules/$moduleSlug'
    | '/academy/admin/modules/create'
    | '/academy/admin/staff/$staffId'
    | '/academy/admin/modules/'
    | '/academy/admin/staff/'
    | '/academy/modules/$moduleSlug/'
    | '/academy/modules/$moduleSlug/lesson/$lessonId'
    | '/academy/admin/modules/$moduleSlug/'
    | '/academy/admin/modules/$moduleSlug/assets/$assetId'
    | '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy/dashboard'
    | '/academy/invite'
    | '/academy/leaderboard'
    | '/academy/profile'
    | '/academy/sign-in'
    | '/academy/admin/ai-review'
    | '/academy/admin/sign-in'
    | '/academy/admin'
    | '/academy/modules'
    | '/academy/admin/modules/create'
    | '/academy/admin/staff/$staffId'
    | '/academy/admin/modules'
    | '/academy/admin/staff'
    | '/academy/modules/$moduleSlug'
    | '/academy/modules/$moduleSlug/lesson/$lessonId'
    | '/academy/admin/modules/$moduleSlug'
    | '/academy/admin/modules/$moduleSlug/assets/$assetId'
    | '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/academy/admin'
    | '/academy/dashboard'
    | '/academy/invite'
    | '/academy/leaderboard'
    | '/academy/modules'
    | '/academy/profile'
    | '/academy/sign-in'
    | '/academy/admin/ai-review'
    | '/academy/admin/modules'
    | '/academy/admin/staff'
    | '/academy/admin_/sign-in'
    | '/academy/modules/$moduleSlug'
    | '/academy/admin/'
    | '/academy/modules/'
    | '/academy/admin/modules/$moduleSlug'
    | '/academy/admin/modules/create'
    | '/academy/admin/staff/$staffId'
    | '/academy/admin/modules/'
    | '/academy/admin/staff/'
    | '/academy/modules/$moduleSlug/'
    | '/academy/modules/$moduleSlug/lesson/$lessonId'
    | '/academy/admin/modules/$moduleSlug/'
    | '/academy/admin/modules/$moduleSlug/assets/$assetId'
    | '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyAdminRoute: typeof AcademyAdminRouteWithChildren
  AcademyDashboardRoute: typeof AcademyDashboardRoute
  AcademyInviteRoute: typeof AcademyInviteRoute
  AcademyLeaderboardRoute: typeof AcademyLeaderboardRoute
  AcademyModulesRoute: typeof AcademyModulesRouteWithChildren
  AcademyProfileRoute: typeof AcademyProfileRoute
  AcademySignInRoute: typeof AcademySignInRoute
  AcademyAdminSignInRoute: typeof AcademyAdminSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/sign-in': {
      id: '/academy/sign-in'
      path: '/academy/sign-in'
      fullPath: '/academy/sign-in'
      preLoaderRoute: typeof AcademySignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/profile': {
      id: '/academy/profile'
      path: '/academy/profile'
      fullPath: '/academy/profile'
      preLoaderRoute: typeof AcademyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/modules': {
      id: '/academy/modules'
      path: '/academy/modules'
      fullPath: '/academy/modules'
      preLoaderRoute: typeof AcademyModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/leaderboard': {
      id: '/academy/leaderboard'
      path: '/academy/leaderboard'
      fullPath: '/academy/leaderboard'
      preLoaderRoute: typeof AcademyLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/invite': {
      id: '/academy/invite'
      path: '/academy/invite'
      fullPath: '/academy/invite'
      preLoaderRoute: typeof AcademyInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/dashboard': {
      id: '/academy/dashboard'
      path: '/academy/dashboard'
      fullPath: '/academy/dashboard'
      preLoaderRoute: typeof AcademyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/admin': {
      id: '/academy/admin'
      path: '/academy/admin'
      fullPath: '/academy/admin'
      preLoaderRoute: typeof AcademyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/modules/': {
      id: '/academy/modules/'
      path: '/'
      fullPath: '/academy/modules/'
      preLoaderRoute: typeof AcademyModulesIndexRouteImport
      parentRoute: typeof AcademyModulesRoute
    }
    '/academy/admin/': {
      id: '/academy/admin/'
      path: '/'
      fullPath: '/academy/admin/'
      preLoaderRoute: typeof AcademyAdminIndexRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/modules/$moduleSlug': {
      id: '/academy/modules/$moduleSlug'
      path: '/$moduleSlug'
      fullPath: '/academy/modules/$moduleSlug'
      preLoaderRoute: typeof AcademyModulesModuleSlugRouteImport
      parentRoute: typeof AcademyModulesRoute
    }
    '/academy/admin_/sign-in': {
      id: '/academy/admin_/sign-in'
      path: '/academy/admin/sign-in'
      fullPath: '/academy/admin/sign-in'
      preLoaderRoute: typeof AcademyAdminSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/admin/staff': {
      id: '/academy/admin/staff'
      path: '/staff'
      fullPath: '/academy/admin/staff'
      preLoaderRoute: typeof AcademyAdminStaffRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/admin/modules': {
      id: '/academy/admin/modules'
      path: '/modules'
      fullPath: '/academy/admin/modules'
      preLoaderRoute: typeof AcademyAdminModulesRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/admin/ai-review': {
      id: '/academy/admin/ai-review'
      path: '/ai-review'
      fullPath: '/academy/admin/ai-review'
      preLoaderRoute: typeof AcademyAdminAiReviewRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/modules/$moduleSlug/': {
      id: '/academy/modules/$moduleSlug/'
      path: '/'
      fullPath: '/academy/modules/$moduleSlug/'
      preLoaderRoute: typeof AcademyModulesModuleSlugIndexRouteImport
      parentRoute: typeof AcademyModulesModuleSlugRoute
    }
    '/academy/admin/staff/': {
      id: '/academy/admin/staff/'
      path: '/'
      fullPath: '/academy/admin/staff/'
      preLoaderRoute: typeof AcademyAdminStaffIndexRouteImport
      parentRoute: typeof AcademyAdminStaffRoute
    }
    '/academy/admin/modules/': {
      id: '/academy/admin/modules/'
      path: '/'
      fullPath: '/academy/admin/modules/'
      preLoaderRoute: typeof AcademyAdminModulesIndexRouteImport
      parentRoute: typeof AcademyAdminModulesRoute
    }
    '/academy/admin/staff/$staffId': {
      id: '/academy/admin/staff/$staffId'
      path: '/$staffId'
      fullPath: '/academy/admin/staff/$staffId'
      preLoaderRoute: typeof AcademyAdminStaffStaffIdRouteImport
      parentRoute: typeof AcademyAdminStaffRoute
    }
    '/academy/admin/modules/create': {
      id: '/academy/admin/modules/create'
      path: '/create'
      fullPath: '/academy/admin/modules/create'
      preLoaderRoute: typeof AcademyAdminModulesCreateRouteImport
      parentRoute: typeof AcademyAdminModulesRoute
    }
    '/academy/admin/modules/$moduleSlug': {
      id: '/academy/admin/modules/$moduleSlug'
      path: '/$moduleSlug'
      fullPath: '/academy/admin/modules/$moduleSlug'
      preLoaderRoute: typeof AcademyAdminModulesModuleSlugRouteImport
      parentRoute: typeof AcademyAdminModulesRoute
    }
    '/academy/admin/modules/$moduleSlug/': {
      id: '/academy/admin/modules/$moduleSlug/'
      path: '/'
      fullPath: '/academy/admin/modules/$moduleSlug/'
      preLoaderRoute: typeof AcademyAdminModulesModuleSlugIndexRouteImport
      parentRoute: typeof AcademyAdminModulesModuleSlugRoute
    }
    '/academy/modules/$moduleSlug/lesson/$lessonId': {
      id: '/academy/modules/$moduleSlug/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/academy/modules/$moduleSlug/lesson/$lessonId'
      preLoaderRoute: typeof AcademyModulesModuleSlugLessonLessonIdRouteImport
      parentRoute: typeof AcademyModulesModuleSlugRoute
    }
    '/academy/admin/modules/$moduleSlug/lessons/$lessonId': {
      id: '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
      preLoaderRoute: typeof AcademyAdminModulesModuleSlugLessonsLessonIdRouteImport
      parentRoute: typeof AcademyAdminModulesModuleSlugRoute
    }
    '/academy/admin/modules/$moduleSlug/assets/$assetId': {
      id: '/academy/admin/modules/$moduleSlug/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/academy/admin/modules/$moduleSlug/assets/$assetId'
      preLoaderRoute: typeof AcademyAdminModulesModuleSlugAssetsAssetIdRouteImport
      parentRoute: typeof AcademyAdminModulesModuleSlugRoute
    }
  }
}

interface AcademyAdminModulesModuleSlugRouteChildren {
  AcademyAdminModulesModuleSlugIndexRoute: typeof AcademyAdminModulesModuleSlugIndexRoute
  AcademyAdminModulesModuleSlugAssetsAssetIdRoute: typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  AcademyAdminModulesModuleSlugLessonsLessonIdRoute: typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}

const AcademyAdminModulesModuleSlugRouteChildren: AcademyAdminModulesModuleSlugRouteChildren =
  {
    AcademyAdminModulesModuleSlugIndexRoute:
      AcademyAdminModulesModuleSlugIndexRoute,
    AcademyAdminModulesModuleSlugAssetsAssetIdRoute:
      AcademyAdminModulesModuleSlugAssetsAssetIdRoute,
    AcademyAdminModulesModuleSlugLessonsLessonIdRoute:
      AcademyAdminModulesModuleSlugLessonsLessonIdRoute,
  }

const AcademyAdminModulesModuleSlugRouteWithChildren =
  AcademyAdminModulesModuleSlugRoute._addFileChildren(
    AcademyAdminModulesModuleSlugRouteChildren,
  )

interface AcademyAdminModulesRouteChildren {
  AcademyAdminModulesModuleSlugRoute: typeof AcademyAdminModulesModuleSlugRouteWithChildren
  AcademyAdminModulesCreateRoute: typeof AcademyAdminModulesCreateRoute
  AcademyAdminModulesIndexRoute: typeof AcademyAdminModulesIndexRoute
}

const AcademyAdminModulesRouteChildren: AcademyAdminModulesRouteChildren = {
  AcademyAdminModulesModuleSlugRoute:
    AcademyAdminModulesModuleSlugRouteWithChildren,
  AcademyAdminModulesCreateRoute: AcademyAdminModulesCreateRoute,
  AcademyAdminModulesIndexRoute: AcademyAdminModulesIndexRoute,
}

const AcademyAdminModulesRouteWithChildren =
  AcademyAdminModulesRoute._addFileChildren(AcademyAdminModulesRouteChildren)

interface AcademyAdminStaffRouteChildren {
  AcademyAdminStaffStaffIdRoute: typeof AcademyAdminStaffStaffIdRoute
  AcademyAdminStaffIndexRoute: typeof AcademyAdminStaffIndexRoute
}

const AcademyAdminStaffRouteChildren: AcademyAdminStaffRouteChildren = {
  AcademyAdminStaffStaffIdRoute: AcademyAdminStaffStaffIdRoute,
  AcademyAdminStaffIndexRoute: AcademyAdminStaffIndexRoute,
}

const AcademyAdminStaffRouteWithChildren =
  AcademyAdminStaffRoute._addFileChildren(AcademyAdminStaffRouteChildren)

interface AcademyAdminRouteChildren {
  AcademyAdminAiReviewRoute: typeof AcademyAdminAiReviewRoute
  AcademyAdminModulesRoute: typeof AcademyAdminModulesRouteWithChildren
  AcademyAdminStaffRoute: typeof AcademyAdminStaffRouteWithChildren
  AcademyAdminIndexRoute: typeof AcademyAdminIndexRoute
}

const AcademyAdminRouteChildren: AcademyAdminRouteChildren = {
  AcademyAdminAiReviewRoute: AcademyAdminAiReviewRoute,
  AcademyAdminModulesRoute: AcademyAdminModulesRouteWithChildren,
  AcademyAdminStaffRoute: AcademyAdminStaffRouteWithChildren,
  AcademyAdminIndexRoute: AcademyAdminIndexRoute,
}

const AcademyAdminRouteWithChildren = AcademyAdminRoute._addFileChildren(
  AcademyAdminRouteChildren,
)

interface AcademyModulesModuleSlugRouteChildren {
  AcademyModulesModuleSlugIndexRoute: typeof AcademyModulesModuleSlugIndexRoute
  AcademyModulesModuleSlugLessonLessonIdRoute: typeof AcademyModulesModuleSlugLessonLessonIdRoute
}

const AcademyModulesModuleSlugRouteChildren: AcademyModulesModuleSlugRouteChildren =
  {
    AcademyModulesModuleSlugIndexRoute: AcademyModulesModuleSlugIndexRoute,
    AcademyModulesModuleSlugLessonLessonIdRoute:
      AcademyModulesModuleSlugLessonLessonIdRoute,
  }

const AcademyModulesModuleSlugRouteWithChildren =
  AcademyModulesModuleSlugRoute._addFileChildren(
    AcademyModulesModuleSlugRouteChildren,
  )

interface AcademyModulesRouteChildren {
  AcademyModulesModuleSlugRoute: typeof AcademyModulesModuleSlugRouteWithChildren
  AcademyModulesIndexRoute: typeof AcademyModulesIndexRoute
}

const AcademyModulesRouteChildren: AcademyModulesRouteChildren = {
  AcademyModulesModuleSlugRoute: AcademyModulesModuleSlugRouteWithChildren,
  AcademyModulesIndexRoute: AcademyModulesIndexRoute,
}

const AcademyModulesRouteWithChildren = AcademyModulesRoute._addFileChildren(
  AcademyModulesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyAdminRoute: AcademyAdminRouteWithChildren,
  AcademyDashboardRoute: AcademyDashboardRoute,
  AcademyInviteRoute: AcademyInviteRoute,
  AcademyLeaderboardRoute: AcademyLeaderboardRoute,
  AcademyModulesRoute: AcademyModulesRouteWithChildren,
  AcademyProfileRoute: AcademyProfileRoute,
  AcademySignInRoute: AcademySignInRoute,
  AcademyAdminSignInRoute: AcademyAdminSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
