/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademySignInRouteImport } from './routes/academy.sign-in'
import { Route as AcademyProfileRouteImport } from './routes/academy.profile'
import { Route as AcademyModulesRouteImport } from './routes/academy.modules'
import { Route as AcademyLeaderboardRouteImport } from './routes/academy.leaderboard'
import { Route as AcademyDashboardRouteImport } from './routes/academy.dashboard'
import { Route as AcademyAdminRouteImport } from './routes/academy.admin'
import { Route as AcademyModulesSocialMediaAwarenessRouteImport } from './routes/academy.modules.social-media-awareness'
import { Route as AcademyModulesModuleSlugRouteImport } from './routes/academy.modules.$moduleSlug'
import { Route as AcademyAdminModulesRouteImport } from './routes/academy.admin.modules'
import { Route as AcademyAdminAiReviewRouteImport } from './routes/academy.admin.ai-review'
import { Route as AcademyModulesSocialMediaSection3RouteImport } from './routes/academy.modules.social-media.section-3'
import { Route as AcademyModulesSocialMediaCompleteRouteImport } from './routes/academy.modules.social-media.complete'
import { Route as AcademyModulesSocialMediaAssessmentRouteImport } from './routes/academy.modules.social-media.assessment'
import { Route as AcademyAdminModulesCreateRouteImport } from './routes/academy.admin.modules.create'
import { Route as AcademyAdminModulesModuleSlugRouteImport } from './routes/academy.admin.modules.$moduleSlug'
import { Route as AcademyModulesModuleSlugLessonLessonIdRouteImport } from './routes/academy.modules.$moduleSlug.lesson.$lessonId'
import { Route as AcademyAdminModulesModuleSlugLessonsLessonIdRouteImport } from './routes/academy.admin.modules.$moduleSlug.lessons.$lessonId'
import { Route as AcademyAdminModulesModuleSlugAssetsAssetIdRouteImport } from './routes/academy.admin.modules.$moduleSlug.assets.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySignInRoute = AcademySignInRouteImport.update({
  id: '/academy/sign-in',
  path: '/academy/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyProfileRoute = AcademyProfileRouteImport.update({
  id: '/academy/profile',
  path: '/academy/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyModulesRoute = AcademyModulesRouteImport.update({
  id: '/academy/modules',
  path: '/academy/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyLeaderboardRoute = AcademyLeaderboardRouteImport.update({
  id: '/academy/leaderboard',
  path: '/academy/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyDashboardRoute = AcademyDashboardRouteImport.update({
  id: '/academy/dashboard',
  path: '/academy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAdminRoute = AcademyAdminRouteImport.update({
  id: '/academy/admin',
  path: '/academy/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyModulesSocialMediaAwarenessRoute =
  AcademyModulesSocialMediaAwarenessRouteImport.update({
    id: '/social-media-awareness',
    path: '/social-media-awareness',
    getParentRoute: () => AcademyModulesRoute,
  } as any)
const AcademyModulesModuleSlugRoute =
  AcademyModulesModuleSlugRouteImport.update({
    id: '/$moduleSlug',
    path: '/$moduleSlug',
    getParentRoute: () => AcademyModulesRoute,
  } as any)
const AcademyAdminModulesRoute = AcademyAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AcademyAdminRoute,
} as any)
const AcademyAdminAiReviewRoute = AcademyAdminAiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => AcademyAdminRoute,
} as any)
const AcademyModulesSocialMediaSection3Route =
  AcademyModulesSocialMediaSection3RouteImport.update({
    id: '/social-media/section-3',
    path: '/social-media/section-3',
    getParentRoute: () => AcademyModulesRoute,
  } as any)
const AcademyModulesSocialMediaCompleteRoute =
  AcademyModulesSocialMediaCompleteRouteImport.update({
    id: '/social-media/complete',
    path: '/social-media/complete',
    getParentRoute: () => AcademyModulesRoute,
  } as any)
const AcademyModulesSocialMediaAssessmentRoute =
  AcademyModulesSocialMediaAssessmentRouteImport.update({
    id: '/social-media/assessment',
    path: '/social-media/assessment',
    getParentRoute: () => AcademyModulesRoute,
  } as any)
const AcademyAdminModulesCreateRoute =
  AcademyAdminModulesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AcademyAdminModulesRoute,
  } as any)
const AcademyAdminModulesModuleSlugRoute =
  AcademyAdminModulesModuleSlugRouteImport.update({
    id: '/$moduleSlug',
    path: '/$moduleSlug',
    getParentRoute: () => AcademyAdminModulesRoute,
  } as any)
const AcademyModulesModuleSlugLessonLessonIdRoute =
  AcademyModulesModuleSlugLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AcademyModulesModuleSlugRoute,
  } as any)
const AcademyAdminModulesModuleSlugLessonsLessonIdRoute =
  AcademyAdminModulesModuleSlugLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AcademyAdminModulesModuleSlugRoute,
  } as any)
const AcademyAdminModulesModuleSlugAssetsAssetIdRoute =
  AcademyAdminModulesModuleSlugAssetsAssetIdRouteImport.update({
    id: '/assets/$assetId',
    path: '/assets/$assetId',
    getParentRoute: () => AcademyAdminModulesModuleSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/leaderboard': typeof AcademyLeaderboardRoute
  '/academy/modules': typeof AcademyModulesRouteWithChildren
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/sign-in': typeof AcademySignInRoute
  '/academy/admin/ai-review': typeof AcademyAdminAiReviewRoute
  '/academy/admin/modules': typeof AcademyAdminModulesRouteWithChildren
  '/academy/modules/$moduleSlug': typeof AcademyModulesModuleSlugRouteWithChildren
  '/academy/modules/social-media-awareness': typeof AcademyModulesSocialMediaAwarenessRoute
  '/academy/admin/modules/$moduleSlug': typeof AcademyAdminModulesModuleSlugRouteWithChildren
  '/academy/admin/modules/create': typeof AcademyAdminModulesCreateRoute
  '/academy/modules/social-media/assessment': typeof AcademyModulesSocialMediaAssessmentRoute
  '/academy/modules/social-media/complete': typeof AcademyModulesSocialMediaCompleteRoute
  '/academy/modules/social-media/section-3': typeof AcademyModulesSocialMediaSection3Route
  '/academy/modules/$moduleSlug/lesson/$lessonId': typeof AcademyModulesModuleSlugLessonLessonIdRoute
  '/academy/admin/modules/$moduleSlug/assets/$assetId': typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  '/academy/admin/modules/$moduleSlug/lessons/$lessonId': typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/leaderboard': typeof AcademyLeaderboardRoute
  '/academy/modules': typeof AcademyModulesRouteWithChildren
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/sign-in': typeof AcademySignInRoute
  '/academy/admin/ai-review': typeof AcademyAdminAiReviewRoute
  '/academy/admin/modules': typeof AcademyAdminModulesRouteWithChildren
  '/academy/modules/$moduleSlug': typeof AcademyModulesModuleSlugRouteWithChildren
  '/academy/modules/social-media-awareness': typeof AcademyModulesSocialMediaAwarenessRoute
  '/academy/admin/modules/$moduleSlug': typeof AcademyAdminModulesModuleSlugRouteWithChildren
  '/academy/admin/modules/create': typeof AcademyAdminModulesCreateRoute
  '/academy/modules/social-media/assessment': typeof AcademyModulesSocialMediaAssessmentRoute
  '/academy/modules/social-media/complete': typeof AcademyModulesSocialMediaCompleteRoute
  '/academy/modules/social-media/section-3': typeof AcademyModulesSocialMediaSection3Route
  '/academy/modules/$moduleSlug/lesson/$lessonId': typeof AcademyModulesModuleSlugLessonLessonIdRoute
  '/academy/admin/modules/$moduleSlug/assets/$assetId': typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  '/academy/admin/modules/$moduleSlug/lessons/$lessonId': typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy/admin': typeof AcademyAdminRouteWithChildren
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/academy/leaderboard': typeof AcademyLeaderboardRoute
  '/academy/modules': typeof AcademyModulesRouteWithChildren
  '/academy/profile': typeof AcademyProfileRoute
  '/academy/sign-in': typeof AcademySignInRoute
  '/academy/admin/ai-review': typeof AcademyAdminAiReviewRoute
  '/academy/admin/modules': typeof AcademyAdminModulesRouteWithChildren
  '/academy/modules/$moduleSlug': typeof AcademyModulesModuleSlugRouteWithChildren
  '/academy/modules/social-media-awareness': typeof AcademyModulesSocialMediaAwarenessRoute
  '/academy/admin/modules/$moduleSlug': typeof AcademyAdminModulesModuleSlugRouteWithChildren
  '/academy/admin/modules/create': typeof AcademyAdminModulesCreateRoute
  '/academy/modules/social-media/assessment': typeof AcademyModulesSocialMediaAssessmentRoute
  '/academy/modules/social-media/complete': typeof AcademyModulesSocialMediaCompleteRoute
  '/academy/modules/social-media/section-3': typeof AcademyModulesSocialMediaSection3Route
  '/academy/modules/$moduleSlug/lesson/$lessonId': typeof AcademyModulesModuleSlugLessonLessonIdRoute
  '/academy/admin/modules/$moduleSlug/assets/$assetId': typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  '/academy/admin/modules/$moduleSlug/lessons/$lessonId': typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy/admin'
    | '/academy/dashboard'
    | '/academy/leaderboard'
    | '/academy/modules'
    | '/academy/profile'
    | '/academy/sign-in'
    | '/academy/admin/ai-review'
    | '/academy/admin/modules'
    | '/academy/modules/$moduleSlug'
    | '/academy/modules/social-media-awareness'
    | '/academy/admin/modules/$moduleSlug'
    | '/academy/admin/modules/create'
    | '/academy/modules/social-media/assessment'
    | '/academy/modules/social-media/complete'
    | '/academy/modules/social-media/section-3'
    | '/academy/modules/$moduleSlug/lesson/$lessonId'
    | '/academy/admin/modules/$moduleSlug/assets/$assetId'
    | '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy/admin'
    | '/academy/dashboard'
    | '/academy/leaderboard'
    | '/academy/modules'
    | '/academy/profile'
    | '/academy/sign-in'
    | '/academy/admin/ai-review'
    | '/academy/admin/modules'
    | '/academy/modules/$moduleSlug'
    | '/academy/modules/social-media-awareness'
    | '/academy/admin/modules/$moduleSlug'
    | '/academy/admin/modules/create'
    | '/academy/modules/social-media/assessment'
    | '/academy/modules/social-media/complete'
    | '/academy/modules/social-media/section-3'
    | '/academy/modules/$moduleSlug/lesson/$lessonId'
    | '/academy/admin/modules/$moduleSlug/assets/$assetId'
    | '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/academy/admin'
    | '/academy/dashboard'
    | '/academy/leaderboard'
    | '/academy/modules'
    | '/academy/profile'
    | '/academy/sign-in'
    | '/academy/admin/ai-review'
    | '/academy/admin/modules'
    | '/academy/modules/$moduleSlug'
    | '/academy/modules/social-media-awareness'
    | '/academy/admin/modules/$moduleSlug'
    | '/academy/admin/modules/create'
    | '/academy/modules/social-media/assessment'
    | '/academy/modules/social-media/complete'
    | '/academy/modules/social-media/section-3'
    | '/academy/modules/$moduleSlug/lesson/$lessonId'
    | '/academy/admin/modules/$moduleSlug/assets/$assetId'
    | '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyAdminRoute: typeof AcademyAdminRouteWithChildren
  AcademyDashboardRoute: typeof AcademyDashboardRoute
  AcademyLeaderboardRoute: typeof AcademyLeaderboardRoute
  AcademyModulesRoute: typeof AcademyModulesRouteWithChildren
  AcademyProfileRoute: typeof AcademyProfileRoute
  AcademySignInRoute: typeof AcademySignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/sign-in': {
      id: '/academy/sign-in'
      path: '/academy/sign-in'
      fullPath: '/academy/sign-in'
      preLoaderRoute: typeof AcademySignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/profile': {
      id: '/academy/profile'
      path: '/academy/profile'
      fullPath: '/academy/profile'
      preLoaderRoute: typeof AcademyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/modules': {
      id: '/academy/modules'
      path: '/academy/modules'
      fullPath: '/academy/modules'
      preLoaderRoute: typeof AcademyModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/leaderboard': {
      id: '/academy/leaderboard'
      path: '/academy/leaderboard'
      fullPath: '/academy/leaderboard'
      preLoaderRoute: typeof AcademyLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/dashboard': {
      id: '/academy/dashboard'
      path: '/academy/dashboard'
      fullPath: '/academy/dashboard'
      preLoaderRoute: typeof AcademyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/admin': {
      id: '/academy/admin'
      path: '/academy/admin'
      fullPath: '/academy/admin'
      preLoaderRoute: typeof AcademyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/modules/social-media-awareness': {
      id: '/academy/modules/social-media-awareness'
      path: '/social-media-awareness'
      fullPath: '/academy/modules/social-media-awareness'
      preLoaderRoute: typeof AcademyModulesSocialMediaAwarenessRouteImport
      parentRoute: typeof AcademyModulesRoute
    }
    '/academy/modules/$moduleSlug': {
      id: '/academy/modules/$moduleSlug'
      path: '/$moduleSlug'
      fullPath: '/academy/modules/$moduleSlug'
      preLoaderRoute: typeof AcademyModulesModuleSlugRouteImport
      parentRoute: typeof AcademyModulesRoute
    }
    '/academy/admin/modules': {
      id: '/academy/admin/modules'
      path: '/modules'
      fullPath: '/academy/admin/modules'
      preLoaderRoute: typeof AcademyAdminModulesRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/admin/ai-review': {
      id: '/academy/admin/ai-review'
      path: '/ai-review'
      fullPath: '/academy/admin/ai-review'
      preLoaderRoute: typeof AcademyAdminAiReviewRouteImport
      parentRoute: typeof AcademyAdminRoute
    }
    '/academy/modules/social-media/section-3': {
      id: '/academy/modules/social-media/section-3'
      path: '/social-media/section-3'
      fullPath: '/academy/modules/social-media/section-3'
      preLoaderRoute: typeof AcademyModulesSocialMediaSection3RouteImport
      parentRoute: typeof AcademyModulesRoute
    }
    '/academy/modules/social-media/complete': {
      id: '/academy/modules/social-media/complete'
      path: '/social-media/complete'
      fullPath: '/academy/modules/social-media/complete'
      preLoaderRoute: typeof AcademyModulesSocialMediaCompleteRouteImport
      parentRoute: typeof AcademyModulesRoute
    }
    '/academy/modules/social-media/assessment': {
      id: '/academy/modules/social-media/assessment'
      path: '/social-media/assessment'
      fullPath: '/academy/modules/social-media/assessment'
      preLoaderRoute: typeof AcademyModulesSocialMediaAssessmentRouteImport
      parentRoute: typeof AcademyModulesRoute
    }
    '/academy/admin/modules/create': {
      id: '/academy/admin/modules/create'
      path: '/create'
      fullPath: '/academy/admin/modules/create'
      preLoaderRoute: typeof AcademyAdminModulesCreateRouteImport
      parentRoute: typeof AcademyAdminModulesRoute
    }
    '/academy/admin/modules/$moduleSlug': {
      id: '/academy/admin/modules/$moduleSlug'
      path: '/$moduleSlug'
      fullPath: '/academy/admin/modules/$moduleSlug'
      preLoaderRoute: typeof AcademyAdminModulesModuleSlugRouteImport
      parentRoute: typeof AcademyAdminModulesRoute
    }
    '/academy/modules/$moduleSlug/lesson/$lessonId': {
      id: '/academy/modules/$moduleSlug/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/academy/modules/$moduleSlug/lesson/$lessonId'
      preLoaderRoute: typeof AcademyModulesModuleSlugLessonLessonIdRouteImport
      parentRoute: typeof AcademyModulesModuleSlugRoute
    }
    '/academy/admin/modules/$moduleSlug/lessons/$lessonId': {
      id: '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/academy/admin/modules/$moduleSlug/lessons/$lessonId'
      preLoaderRoute: typeof AcademyAdminModulesModuleSlugLessonsLessonIdRouteImport
      parentRoute: typeof AcademyAdminModulesModuleSlugRoute
    }
    '/academy/admin/modules/$moduleSlug/assets/$assetId': {
      id: '/academy/admin/modules/$moduleSlug/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/academy/admin/modules/$moduleSlug/assets/$assetId'
      preLoaderRoute: typeof AcademyAdminModulesModuleSlugAssetsAssetIdRouteImport
      parentRoute: typeof AcademyAdminModulesModuleSlugRoute
    }
  }
}

interface AcademyAdminModulesModuleSlugRouteChildren {
  AcademyAdminModulesModuleSlugAssetsAssetIdRoute: typeof AcademyAdminModulesModuleSlugAssetsAssetIdRoute
  AcademyAdminModulesModuleSlugLessonsLessonIdRoute: typeof AcademyAdminModulesModuleSlugLessonsLessonIdRoute
}

const AcademyAdminModulesModuleSlugRouteChildren: AcademyAdminModulesModuleSlugRouteChildren =
  {
    AcademyAdminModulesModuleSlugAssetsAssetIdRoute:
      AcademyAdminModulesModuleSlugAssetsAssetIdRoute,
    AcademyAdminModulesModuleSlugLessonsLessonIdRoute:
      AcademyAdminModulesModuleSlugLessonsLessonIdRoute,
  }

const AcademyAdminModulesModuleSlugRouteWithChildren =
  AcademyAdminModulesModuleSlugRoute._addFileChildren(
    AcademyAdminModulesModuleSlugRouteChildren,
  )

interface AcademyAdminModulesRouteChildren {
  AcademyAdminModulesModuleSlugRoute: typeof AcademyAdminModulesModuleSlugRouteWithChildren
  AcademyAdminModulesCreateRoute: typeof AcademyAdminModulesCreateRoute
}

const AcademyAdminModulesRouteChildren: AcademyAdminModulesRouteChildren = {
  AcademyAdminModulesModuleSlugRoute:
    AcademyAdminModulesModuleSlugRouteWithChildren,
  AcademyAdminModulesCreateRoute: AcademyAdminModulesCreateRoute,
}

const AcademyAdminModulesRouteWithChildren =
  AcademyAdminModulesRoute._addFileChildren(AcademyAdminModulesRouteChildren)

interface AcademyAdminRouteChildren {
  AcademyAdminAiReviewRoute: typeof AcademyAdminAiReviewRoute
  AcademyAdminModulesRoute: typeof AcademyAdminModulesRouteWithChildren
}

const AcademyAdminRouteChildren: AcademyAdminRouteChildren = {
  AcademyAdminAiReviewRoute: AcademyAdminAiReviewRoute,
  AcademyAdminModulesRoute: AcademyAdminModulesRouteWithChildren,
}

const AcademyAdminRouteWithChildren = AcademyAdminRoute._addFileChildren(
  AcademyAdminRouteChildren,
)

interface AcademyModulesModuleSlugRouteChildren {
  AcademyModulesModuleSlugLessonLessonIdRoute: typeof AcademyModulesModuleSlugLessonLessonIdRoute
}

const AcademyModulesModuleSlugRouteChildren: AcademyModulesModuleSlugRouteChildren =
  {
    AcademyModulesModuleSlugLessonLessonIdRoute:
      AcademyModulesModuleSlugLessonLessonIdRoute,
  }

const AcademyModulesModuleSlugRouteWithChildren =
  AcademyModulesModuleSlugRoute._addFileChildren(
    AcademyModulesModuleSlugRouteChildren,
  )

interface AcademyModulesRouteChildren {
  AcademyModulesModuleSlugRoute: typeof AcademyModulesModuleSlugRouteWithChildren
  AcademyModulesSocialMediaAwarenessRoute: typeof AcademyModulesSocialMediaAwarenessRoute
  AcademyModulesSocialMediaAssessmentRoute: typeof AcademyModulesSocialMediaAssessmentRoute
  AcademyModulesSocialMediaCompleteRoute: typeof AcademyModulesSocialMediaCompleteRoute
  AcademyModulesSocialMediaSection3Route: typeof AcademyModulesSocialMediaSection3Route
}

const AcademyModulesRouteChildren: AcademyModulesRouteChildren = {
  AcademyModulesModuleSlugRoute: AcademyModulesModuleSlugRouteWithChildren,
  AcademyModulesSocialMediaAwarenessRoute:
    AcademyModulesSocialMediaAwarenessRoute,
  AcademyModulesSocialMediaAssessmentRoute:
    AcademyModulesSocialMediaAssessmentRoute,
  AcademyModulesSocialMediaCompleteRoute:
    AcademyModulesSocialMediaCompleteRoute,
  AcademyModulesSocialMediaSection3Route:
    AcademyModulesSocialMediaSection3Route,
}

const AcademyModulesRouteWithChildren = AcademyModulesRoute._addFileChildren(
  AcademyModulesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyAdminRoute: AcademyAdminRouteWithChildren,
  AcademyDashboardRoute: AcademyDashboardRoute,
  AcademyLeaderboardRoute: AcademyLeaderboardRoute,
  AcademyModulesRoute: AcademyModulesRouteWithChildren,
  AcademyProfileRoute: AcademyProfileRoute,
  AcademySignInRoute: AcademySignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
